In [ ]:
# NUMPY MASTER CLASS FOR DATA SCIENCE:-

In [ ]:
'''
1. why array doesn't contains , between the elements and list does?
List: Designed for general-purpose storage and manipulation of heterogeneous data (like numbers, strings, etc.), and Python prints it with commas to indicate a collection of separate items.
Array: NumPy arrays are optimized for numerical operations, and when printed, they are displayed without commas for simplicity and mathematical consistency.
'''

In [11]:
import numpy as np

lst = [1,2,3,4,5]
print(type(lst)) # <class 'list'>
arr = np.array(lst)
print(arr) # [1 2 3 4 5]
print(lst) # [1, 2, 3, 4, 5]
print(type(arr)) # <class 'numpy.ndarray'>
arr.shape # --> it's basically definer the shape of array is one-dimension or not


<class 'list'>
[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>


(5,)

In [14]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1.shape # --> (2, 3) contains (2rows, 3columns)

# change shape only with total number of elements which contains the array.
arr1.reshape(3, 2)
arr1.reshape(1, 6)
arr1.reshape(6, 1)
arr1.reshape(2, 3)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
# tuple
tp = np.array((1,2,3,4))
print(tp)
tp.dtype

[1 2 3 4]


dtype('int32')

In [24]:
# change dictionary into the array
dic = {
    'a': 1,
    'b': 2,
    'c': 3
}
print(dic)
print(type(dic))

# dit = np.array(dic)
# print(dit)
# print(type(dit))

# convert dictionary values into the array 
value_arr = np.array(list(dic.values()))
# convert dictionary keys into the array 
key_arr = np.array(list(dic.keys()))
print(value_arr)
print(key_arr)

# convert dictionary keys and values into the two-dimenssion array
dic_arr = np.array(list(dic.items()))
print(dic_arr)
print(type(dic_arr))

{'a': 1, 'b': 2, 'c': 3}
<class 'dict'>
[1 2 3]
['a' 'b' 'c']
[['a' '1']
 ['b' '2']
 ['c' '3']]
<class 'numpy.ndarray'>


In [37]:
# how to create an array from scratch

np.arange(1, 10) # array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a1 = np.arange(1, 10, 2) # array([1, 3, 5, 7, 9])
print(a1)

a1.shape
a2 = a1.reshape(5, 1)
a2.reshape(1, 5) # array([[1, 3, 5, 7, 9]])



[1 3 5 7 9]


array([[1, 3, 5, 7, 9]])

In [38]:
# create an array in the reverse order using arange() method
rev = np.arange(50, 1, -2)
print(rev) # [50]


[50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])