In [ ]:
# NUMPY MASTER CLASS FOR DATA SCIENCE:-

In [ ]:
'''
1. why array doesn't contains , between the elements and list does?
List: Designed for general-purpose storage and manipulation of heterogeneous data (like numbers, strings, etc.), and Python prints it with commas to indicate a collection of separate items.
Array: NumPy arrays are optimized for numerical operations, and when printed, they are displayed without commas for simplicity and mathematical consistency.
'''

In [2]:
import numpy as np

lst = [1,2,3,4,5]
print(type(lst)) # <class 'list'>
arr = np.array(lst)
print(arr) # [1 2 3 4 5]
print(lst) # [1, 2, 3, 4, 5]
print(type(arr)) # <class 'numpy.ndarray'>
arr.shape # --> it's basically definer the shape of array is one-dimension or not


<class 'list'>
[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>


(5,)

In [14]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1.shape # --> (2, 3) contains (2rows, 3columns)

# change shape only with total number of elements which contains the array.
arr1.reshape(3, 2)
arr1.reshape(1, 6)
arr1.reshape(6, 1)
arr1.reshape(2, 3)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
# tuple
tp = np.array((1,2,3,4))
print(tp)
tp.dtype

[1 2 3 4]


dtype('int32')

In [24]:
# change dictionary into the array
dic = {
    'a': 1,
    'b': 2,
    'c': 3
}
print(dic)
print(type(dic))

# dit = np.array(dic)
# print(dit)
# print(type(dit))

# convert dictionary values into the array 
value_arr = np.array(list(dic.values()))
# convert dictionary keys into the array 
key_arr = np.array(list(dic.keys()))
print(value_arr)
print(key_arr)

# convert dictionary keys and values into the two-dimenssion array
dic_arr = np.array(list(dic.items()))
print(dic_arr)
print(type(dic_arr))

{'a': 1, 'b': 2, 'c': 3}
<class 'dict'>
[1 2 3]
['a' 'b' 'c']
[['a' '1']
 ['b' '2']
 ['c' '3']]
<class 'numpy.ndarray'>


In [37]:
# how to create an array from scratch

np.arange(1, 10) # array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a1 = np.arange(1, 10, 2) # array([1, 3, 5, 7, 9])
print(a1) # [1 3 5 7 9]

a1.shape
a2 = a1.reshape(5, 1)
a2.reshape(1, 5) # array([[1, 3, 5, 7, 9]])



[1 3 5 7 9]


array([[1, 3, 5, 7, 9]])

In [3]:
# create an array in the reverse order using arange() method
rev = np.arange(50, 1, -2)
print(rev) # [50 48 46 44 42 40 38 36 34 .... 2]


[50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2]


In [6]:
# create an equaly space elements of array

np.linspace(1, 20, 40).reshape(2, 20)

array([[ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
         3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
         5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
         8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026],
       [10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
        13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
        15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
        18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ]])

In [9]:
zeros = np.zeros((3,2))
print(zeros) 
np.zeros(5) # array([0., 0., 0., 0., 0.]) numpy array gives us value in the floating point by default

one = np.ones((2, 2))
print(one)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [12]:
# create identity matrix
np.eye(2)
np.identity(3) # both are same for generating the identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
print('Random number generation (uniform distribution)')


# Generate a 3x3 matrix with uniform distribution between 0 and 1
uniform_matrix = np.random.uniform(0, 1, (3, 3))
print(uniform_matrix)
matrix2 = np.random.rand(3, 3)
print(matrix2)

# Generate a 3x3 matrix with non-uniform distribution (normal distribution) with mean = 0 qne standard deviation = 1
non_uniform_matrix = np.random.normal(0, 1, (3, 3))
print(non_uniform_matrix)



Random number generation (uniform distribution)
[[0.40173745 0.30977522 0.53676239]
 [0.2558723  0.99553576 0.31978639]
 [0.21719417 0.73545493 0.819386  ]]
[[0.42441998 0.57533807 0.09496236]
 [0.52969985 0.1979053  0.27641989]
 [0.2425783  0.61212602 0.70237231]]
[[ 0.77107087  1.18512235 -1.07889231]
 [-0.12654764 -0.50036471  1.47803161]
 [-2.1429077  -1.57802458 -0.3092241 ]]


In [19]:
# create a random number between 1 to 100
ran = np.random.randint(1, 20)
print(ran)
np.random.randint(1, 100, 20) # (start, end, total_random_number)

2


array([20, 93, 50, 49, 84, 13, 30, 87, 98, 98,  6, 45, 98, 62, 77, 23, 79,
       22, 99, 88])

In [24]:
ar = np.arange(1, 11)
print(ar)
# slicing the array elements
print(ar[1: ])
print(ar[1: 6])
print(ar[1: 4])
print(ar[-1: 3]) # [] empty array
print(ar[-1: 3: -1])

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]
[2 3 4 5 6]
[2 3 4]
[]
[10  9  8  7  6  5]


In [32]:
arrr = np.random.randint(1, 100, 20).reshape(5,4)
print(arrr)

arrr[0:3, 0:3]
arrr[3: , 1: ]


[[66 27 85 64]
 [66 50 16 73]
 [99 64 92 78]
 [89 31 20 80]
 [76 67 94  1]]


array([[31, 20, 80],
       [67, 94,  1]])

In [33]:
# universal functions

a = np.random.randint(1, 100, (3, 3))
b = np.random.randint(20, 100, (3, 3))
print(a)
print(b)


[[15 73  9]
 [67 21  7]
 [81 38 99]]
[[51 84 53]
 [43 28 49]
 [99 51 69]]


In [34]:
a + b

array([[ 66, 157,  62],
       [110,  49,  56],
       [180,  89, 168]])

In [35]:
a * b

array([[ 765, 6132,  477],
       [2881,  588,  343],
       [8019, 1938, 6831]])

In [36]:
a / b

array([[0.29411765, 0.86904762, 0.16981132],
       [1.55813953, 0.75      , 0.14285714],
       [0.81818182, 0.74509804, 1.43478261]])

In [38]:
# inbuilt functions:-

np.sqrt(a)

array([[3.87298335, 8.54400375, 3.        ],
       [8.18535277, 4.58257569, 2.64575131],
       [9.        , 6.164414  , 9.94987437]])

In [41]:
# brodcasting

c = np.arange(1, 11)
print(c)

c[2: ] = 1000
print(c)


[ 1  2  3  4  5  6  7  8  9 10]
[   1    2 1000 1000 1000 1000 1000 1000 1000 1000]
