In [19]:

import numpy as nm

arr = nm.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
l1 = [1,2,3,4]
l2 = [1,2,3,4]
l3 = [1,2,3,4]

nm.array([l1, l2, l3])


<module 'numpy' from 'c:\\Users\\HARSH\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>


In [1]:
import pandas as pd
import numpy as np

arr = np.arange(0, 20).reshape(5, 4)
print(arr)

df = pd.DataFrame(arr, index = ["row1", "row2", "row3", "row4", "row5"], columns = ["col1", "col2", "col3", "col4"] )

df.info()
df.head()


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int32
 1   col2    5 non-null      int32
 2   col3    5 non-null      int32
 3   col4    5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [14]:
df.iloc[0:]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [2]:
# if you want to take only one column with column name...
one = df['col1']
print(type(one))


<class 'pandas.core.series.Series'>


In [10]:
# if you want to fetch multiple columns with column name...
two = df[['col1', 'col4' ]]
print(two)
print(type(two))

      col1  col4
row1     0     3
row2     4     7
row3     8    11
row4    12    15
row5    16    19
<class 'pandas.core.frame.DataFrame'>


In [12]:
# if you want to fetch only one row with row index...
singleRow = df.loc['row1']
print(singleRow)
print(type(singleRow))

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int32
<class 'pandas.core.series.Series'>


In [13]:
# if you want to fetch multiple rows with row index...
multipleRows = df.loc[['row1', 'row2', 'row3']]
print(multipleRows)
print(type(multipleRows))

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
<class 'pandas.core.frame.DataFrame'>


In [14]:
print(df)

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19


In [15]:
df.iloc[ 2:4, 0:2]

col1  col2
row3     8     9
row4    12    13

In [17]:
df.iloc[:, [0, 3]] # first method
df[['col1', 'col4']] # second method


col1  col4
row1     0     3
row2     4     7
row3     8    11
row4    12    15
row5    16    19

In [18]:
# convert dataframes into array...
df[['col1', 'col4']].values

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15],
       [16, 19]])

In [ ]:
# Basic operations...
