In [7]:
# introduction of pandas:-
# pandas dataframe
# pandas series 

import pandas as pd

arr = [[1, 2, 3], [4,5,6]]

# create dataframe
df = pd.DataFrame(arr, columns=['col', 'col2', 'col3'])
print(df)


   col  col2  col3
0    1     2     3
1    4     5     6


In [13]:
import numpy as np

a = np.arange(1, 21).reshape(5, 4)
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [19]:
df2 = pd.DataFrame(a, index=['r1', 'r2', 'r3', 'r4', 'r5'], columns=['c1', 'c2', 'c3', 'c4'])
print(df2)

    c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17  18  19  20


In [23]:
# get top 5 records
df2.head(1)
df2.head(2)
df2.head(3)
df2.head(4)
df2.head()

# get last top 5 records, basically its gives in descending order:- 
df2.tail(1) # last row
df2.tail(2) # last second row
df2.tail(3) # last third row
df2.tail(4) # last fourth row
df2.tail() # last fifth

c1  c2  c3  c4
r5  17  18  19  20

In [24]:
df2.describe()

c1         c2         c3         c4
count   5.000000   5.000000   5.000000   5.000000
mean    9.000000  10.000000  11.000000  12.000000
std     6.324555   6.324555   6.324555   6.324555
min     1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000
50%     9.000000  10.000000  11.000000  12.000000
75%    13.000000  14.000000  15.000000  16.000000
max    17.000000  18.000000  19.000000  20.000000

In [28]:
# indexing

col = df2[['c1', 'c2']] # --> in this case if we pass col as a 2d df so it's called as dataframes.
print(col)
print(type(col)) 


col2 = df2['c1'] # --> in this case if you want to take one column or row so it's called as series.
print(col2)
print(type(col2)) 

    c1  c2
r1   1   2
r2   5   6
r3   9  10
r4  13  14
r5  17  18
<class 'pandas.core.frame.DataFrame'>
r1     1
r2     5
r3     9
r4    13
r5    17
Name: c1, dtype: int32
<class 'pandas.core.series.Series'>


In [29]:
# retreive rows from df

# location --> if you know the index name you can use loc method by passing the indexes.
df2.loc[['r1', 'r2']]

c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8

In [34]:
# index location using slicing
# if you don't know the name of indexes you can use iloc method for fetching the data.
df2.iloc[0:3, 0:2]

c1  c2
r1   1   2
r2   5   6
r3   9  10

In [37]:
df2.iloc[2:4, 1:3]

c2  c3
r3  10  11
r4  14  15

In [43]:
# convert data frame to array
df2.iloc[2:4, 1:3].values

array([[10, 11],
       [14, 15]])